// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git.sql

package dbgen

import (
	"context"
	"time"
)

const deleteGitConfig = `-- name: DeleteGitConfig :exec
DELETE FROM git_config WHERE fingerprint = ?
`

func (q *Queries) DeleteGitConfig(ctx context.Context, fingerprint string) error {
	_, err := q.db.ExecContext(ctx, deleteGitConfig, fingerprint)
	return err
}

const getGitConfig = `-- name: GetGitConfig :one
SELECT fingerprint, repo_url, encrypted_pat, created_at, updated_at, branch FROM git_config WHERE fingerprint = ?
`

func (q *Queries) GetGitConfig(ctx context.Context, fingerprint string) (GitConfig, error) {
	row := q.db.QueryRowContext(ctx, getGitConfig, fingerprint)
	var i GitConfig
	err := row.Scan(
		&i.Fingerprint,
		&i.RepoUrl,
		&i.EncryptedPat,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Branch,
	)
	return i, err
}

const getGitSyncStatus = `-- name: GetGitSyncStatus :one
SELECT
    gc.fingerprint,
    gc.repo_url,
    gc.branch,
    gc.encrypted_pat,
    gc.created_at as config_created_at,
    (SELECT COUNT(*) FROM git_sync_log WHERE fingerprint = gc.fingerprint AND status = 'success') as success_count,
    (SELECT COUNT(*) FROM git_sync_log WHERE fingerprint = gc.fingerprint AND status = 'failed') as failed_count
FROM git_config gc
WHERE gc.fingerprint = ?
`

type GetGitSyncStatusRow struct {
	Fingerprint     string    `json:"fingerprint"`
	RepoUrl         string    `json:"repo_url"`
	Branch          string    `json:"branch"`
	EncryptedPat    string    `json:"encrypted_pat"`
	ConfigCreatedAt time.Time `json:"config_created_at"`
	SuccessCount    int64     `json:"success_count"`
	FailedCount     int64     `json:"failed_count"`
}

func (q *Queries) GetGitSyncStatus(ctx context.Context, fingerprint string) (GetGitSyncStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getGitSyncStatus, fingerprint)
	var i GetGitSyncStatusRow
	err := row.Scan(
		&i.Fingerprint,
		&i.RepoUrl,
		&i.Branch,
		&i.EncryptedPat,
		&i.ConfigCreatedAt,
		&i.SuccessCount,
		&i.FailedCount,
	)
	return i, err
}

const listGitSyncLog = `-- name: ListGitSyncLog :many
SELECT id, fingerprint, operation, status, message, entries_changed, created_at FROM git_sync_log
WHERE fingerprint = ?
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListGitSyncLog(ctx context.Context, fingerprint string) ([]GitSyncLog, error) {
	rows, err := q.db.QueryContext(ctx, listGitSyncLog, fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitSyncLog{}
	for rows.Next() {
		var i GitSyncLog
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Operation,
			&i.Status,
			&i.Message,
			&i.EntriesChanged,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logGitSync = `-- name: LogGitSync :exec
INSERT INTO git_sync_log (fingerprint, operation, status, message, entries_changed)
VALUES (?, ?, ?, ?, ?)
`

type LogGitSyncParams struct {
	Fingerprint    string  `json:"fingerprint"`
	Operation      string  `json:"operation"`
	Status         string  `json:"status"`
	Message        *string `json:"message"`
	EntriesChanged *int64  `json:"entries_changed"`
}

func (q *Queries) LogGitSync(ctx context.Context, arg LogGitSyncParams) error {
	_, err := q.db.ExecContext(ctx, logGitSync,
		arg.Fingerprint,
		arg.Operation,
		arg.Status,
		arg.Message,
		arg.EntriesChanged,
	)
	return err
}

const updateGitEncryptedPat = `-- name: UpdateGitEncryptedPat :exec
UPDATE git_config
SET encrypted_pat = ?, updated_at = CURRENT_TIMESTAMP
WHERE fingerprint = ?
`

type UpdateGitEncryptedPatParams struct {
	EncryptedPat string `json:"encrypted_pat"`
	Fingerprint  string `json:"fingerprint"`
}

func (q *Queries) UpdateGitEncryptedPat(ctx context.Context, arg UpdateGitEncryptedPatParams) error {
	_, err := q.db.ExecContext(ctx, updateGitEncryptedPat, arg.EncryptedPat, arg.Fingerprint)
	return err
}

const upsertGitConfig = `-- name: UpsertGitConfig :exec
INSERT INTO git_config (fingerprint, repo_url, branch, encrypted_pat, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (fingerprint) DO UPDATE
SET repo_url = excluded.repo_url,
    branch = excluded.branch,
    encrypted_pat = excluded.encrypted_pat,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertGitConfigParams struct {
	Fingerprint  string `json:"fingerprint"`
	RepoUrl      string `json:"repo_url"`
	Branch       string `json:"branch"`
	EncryptedPat string `json:"encrypted_pat"`
}

func (q *Queries) UpsertGitConfig(ctx context.Context, arg UpsertGitConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitConfig,
		arg.Fingerprint,
		arg.RepoUrl,
		arg.Branch,
		arg.EncryptedPat,
	)
	return err
}
