// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Entry struct {
	ID          int64      `json:"id"`
	Fingerprint string     `json:"fingerprint"`
	Path        string     `json:"path"`
	Content     []byte     `json:"content"`
	Created     *time.Time `json:"created"`
	Updated     *time.Time `json:"updated"`
}

type GitConfig struct {
	Fingerprint  string    `json:"fingerprint"`
	RepoUrl      string    `json:"repo_url"`
	EncryptedPat string    `json:"encrypted_pat"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Branch       string    `json:"branch"`
}

type GitSyncLog struct {
	ID             int64     `json:"id"`
	Fingerprint    string    `json:"fingerprint"`
	Operation      string    `json:"operation"`
	Status         string    `json:"status"`
	Message        *string   `json:"message"`
	EntriesChanged *int64    `json:"entries_changed"`
	CreatedAt      time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type User struct {
	Fingerprint  string     `json:"fingerprint"`
	PasswordHash string     `json:"password_hash"`
	PublicKey    string     `json:"public_key"`
	TotpSecret   *string    `json:"totp_secret"`
	TotpEnabled  *int64     `json:"totp_enabled"`
	Created      *time.Time `json:"created"`
	LoginTime    *time.Time `json:"login_time"`
	LastActivity *time.Time `json:"last_activity"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
