// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webpass.sql

package dbgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (fingerprint, password_hash, public_key)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Fingerprint  string `json:"fingerprint"`
	PasswordHash string `json:"password_hash"`
	PublicKey    string `json:"public_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Fingerprint, arg.PasswordHash, arg.PublicKey)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE fingerprint = ? AND path = ?
`

type DeleteEntryParams struct {
	Fingerprint string `json:"fingerprint"`
	Path        string `json:"path"`
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, arg.Fingerprint, arg.Path)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE fingerprint = ?
`

func (q *Queries) DeleteUser(ctx context.Context, fingerprint string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, fingerprint)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, fingerprint, path, content, created, updated FROM entries
WHERE fingerprint = ? AND path = ?
`

type GetEntryParams struct {
	Fingerprint string `json:"fingerprint"`
	Path        string `json:"path"`
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.Fingerprint, arg.Path)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Path,
		&i.Content,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT fingerprint, password_hash, public_key, totp_secret, totp_enabled, created FROM users WHERE fingerprint = ?
`

func (q *Queries) GetUser(ctx context.Context, fingerprint string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, fingerprint)
	var i User
	err := row.Scan(
		&i.Fingerprint,
		&i.PasswordHash,
		&i.PublicKey,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Created,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, fingerprint, path, created, updated
FROM entries
WHERE fingerprint = ?
ORDER BY path
`

type ListEntriesRow struct {
	ID          int64      `json:"id"`
	Fingerprint string     `json:"fingerprint"`
	Path        string     `json:"path"`
	Created     *time.Time `json:"created"`
	Updated     *time.Time `json:"updated"`
}

func (q *Queries) ListEntries(ctx context.Context, fingerprint string) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesRow{}
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Path,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesContent = `-- name: ListEntriesContent :many
SELECT id, fingerprint, path, content, created, updated FROM entries
WHERE fingerprint = ?
ORDER BY path
`

func (q *Queries) ListEntriesContent(ctx context.Context, fingerprint string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesContent, fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Path,
			&i.Content,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveEntry = `-- name: MoveEntry :exec
UPDATE entries
SET path = ?, updated = CURRENT_TIMESTAMP
WHERE fingerprint = ? AND path = ?
`

type MoveEntryParams struct {
	Path        string `json:"path"`
	Fingerprint string `json:"fingerprint"`
	Path_2      string `json:"path_2"`
}

func (q *Queries) MoveEntry(ctx context.Context, arg MoveEntryParams) error {
	_, err := q.db.ExecContext(ctx, moveEntry, arg.Path, arg.Fingerprint, arg.Path_2)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = ?
WHERE fingerprint = ?
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Fingerprint  string `json:"fingerprint"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.Fingerprint)
	return err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :exec
UPDATE users
SET totp_secret = ?, totp_enabled = ?
WHERE fingerprint = ?
`

type UpdateUserTOTPParams struct {
	TotpSecret  *string `json:"totp_secret"`
	TotpEnabled *int64  `json:"totp_enabled"`
	Fingerprint string  `json:"fingerprint"`
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTOTP, arg.TotpSecret, arg.TotpEnabled, arg.Fingerprint)
	return err
}

const upsertEntry = `-- name: UpsertEntry :exec
INSERT INTO entries (fingerprint, path, content, created, updated)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (fingerprint, path) DO UPDATE
SET content = excluded.content,
    updated = CURRENT_TIMESTAMP
`

type UpsertEntryParams struct {
	Fingerprint string `json:"fingerprint"`
	Path        string `json:"path"`
	Content     []byte `json:"content"`
}

func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntry, arg.Fingerprint, arg.Path, arg.Content)
	return err
}
